# Generated by Django 4.2.7 on 2023-11-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_driving_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driving_license_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='driving_license_id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='government_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='government_id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='secondname'),
        ),
    ]
