# Generated by Django 4.2.7 on 2023-11-22 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0002_alter_qotaq_qotaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuelAmount', models.CharField(max_length=255, verbose_name='origin')),
                ('fuelType', models.CharField(max_length=255, verbose_name='origin')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 20, 52, 20, 811459), verbose_name='created_time')),
                ('gas_station', models.CharField(blank=True, max_length=255, null=True, verbose_name='gas_station')),
                ('fueling_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_description', models.CharField(max_length=255, verbose_name='maintenance_description')),
                ('maintenance_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='origin')),
                ('destination', models.CharField(max_length=255, verbose_name='origin')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 20, 52, 20, 811302), verbose_name='start_time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end_time')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 20, 52, 20, 811311), verbose_name='created_time')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('license_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='license_plate')),
                ('seating_capacity', models.IntegerField(blank=True, null=True, verbose_name='seating_capacity')),
                ('vin', models.CharField(blank=True, max_length=35, null=True, verbose_name='vin')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('status', models.CharField(blank=True, max_length=55, null=True, verbose_name='status')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 11, 22, 20, 52, 20, 811157), verbose_name='created_time')),
            ],
        ),
        migrations.DeleteModel(
            name='Qotaq',
        ),
    ]
