# Generated by Django 4.2.7 on 2023-11-27 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fuelingservice_maintenanceservice_route_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelingservice',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 18, 26, 40, 638901), verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 18, 26, 40, 638756), verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 18, 26, 40, 638748), verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 18, 26, 40, 638604), verbose_name='created_time'),
        ),
    ]
