# Generated by Django 4.2.7 on 2023-11-28 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_alter_fuelingservice_created_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="photo",
        ),
        migrations.AlterField(
            model_name="fuelingservice",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 7, 51, 50, 877732),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 7, 51, 50, 877588),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 7, 51, 50, 877580),
                verbose_name="start_time",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 7, 51, 50, 877461),
                verbose_name="created_time",
            ),
        ),
    ]
