# Generated by Django 4.2.7 on 2023-11-30 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0005_remove_vehicle_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelingservice",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 16, 0, 55, 680933),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 16, 0, 55, 680794),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 16, 0, 55, 680786),
                verbose_name="start_time",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 16, 0, 55, 680664),
                verbose_name="created_time",
            ),
        ),
    ]
