# Generated by Django 4.2.7 on 2023-12-01 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0006_alter_fuelingservice_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelingservice",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 7, 37, 26, 503035),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 7, 37, 26, 502901),
                verbose_name="created_time",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 7, 37, 26, 502893),
                verbose_name="start_time",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 1, 7, 37, 26, 502779),
                verbose_name="created_time",
            ),
        ),
    ]
